### ISSUE TITLE
Typescript definition getClose()

### ISSUE THREAD

**Issue by maku** [bibizio/svelte-dialogs#1]
I think the definition is not correct. It should be:

`export function getClose(): (data: any) => void;`

**Comment by bibizio** [comment]
Hi!
You're right, thank you! I'm reviewing all the types since I may have made some mistakes.... I'll release a fixed version as soon as I can.

**Comment by maku** [comment]
@bibizio thank you, great work... Do you have considered to write the lib in typescript?  But in general I really like "svelte-dialogs". By far the best I saw regarding svelte and dialogs...

**Comment by bibizio** [comment]
@maku thank you :)
rewriting in typescript is in the to-do list!
