### ISSUE TITLE
Problem with dialogs.alert

### ISSUE THREAD

**Issue by andreock** [bibizio/svelte-dialogs#2]
Hi, when I try to call the dialogs.prompt function it returns this error:
![image](https://user-images.githubusercontent.com/26500347/175777763-f72c2658-529b-4307-90cd-0b6eace1d544.png)
Do you know how to solve?
This is the code: 
 dialogs.prompt("Quanti sacchetti da 250G vuoi ordinare?").then(()=>{
//code
});

**Comment by bibizio** [comment]
Hi!
If you're using an old version of some browsers, the crypto module may not have the randomUUID method (see the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)).
What browser[version] are you using?
I'll add a fallback in the next release, but in the meantime you can try updating your browser and see if it fixes the problem.

**Comment by andreock** [comment]
I'm using Chrome 103.0.5060.53 on MacOS, also on Safari doesn't work crypto.randomUUID.
Now i resolve using math.random instead of crypto.randomUUID

**Comment by bibizio** [comment]
I replaced crypto.randomUUID with a simpler function to generate random ids in v1.2.2
