### ISSUE TITLE
Dialogs.prompt is not responsive

### ISSUE THREAD

**Issue by andreock** [bibizio/svelte-dialogs#3]
Hi, I wanted to report a small bug that is in the dialogs.prompt function, on mobile devices, the prompt window has buttons out of position.
![photo_2022-06-27 11 25 16 (1)](https://user-images.githubusercontent.com/26500347/175907075-f4ffd200-71cd-4365-9673-27b14e63617b.jpeg)

**Comment by bibizio** [comment]
It should be fixed in v1.2.2
Also, I suggest you should use a title option and an empty label if there is only one input and a very long label:
```
dialogs.prompt("", {title: "Quanti sacchetti da 250g vuoi ordinare?"})
```
