### ISSUE TITLE
confirm dialogue has no buttons when providing options

### ISSUE THREAD

**Issue by ChristianSch** [bibizio/svelte-dialogs#4]
Expected: dialogue has two buttons (delete, abort) according to the config.
Actual: no buttons are being displayed
Notes: this code is inside a route, not a component

```
<script lang="ts">
    import { dialogs } from 'svelte-dialogs';

    async function deleteUser() {
        console.log('delete user');
        const isConfirmed = await dialogs.confirm({
            content: 'Do you want to delete your account?',
            confirmButtonText: 'Delete',
            declineButtonText: 'Abort',
            closeOnBg: true,
            closeOnEsc: true
        });
        if (!isConfirmed) return;
        // ...
        });
</script>

<button
    on:click|preventDefault={deleteUser}
    class="bg-red-400 text-white active:bg-red-500 text-sm font-bold uppercase px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 w-full ease-linear transition-all duration-150"
    >Delete your account</button
>
```

![image](https://user-images.githubusercontent.com/6138133/183666307-9636d632-82ae-4273-b0dc-05aed0d41b12.png)

**Comment by ChristianSch** [comment]
I quickly tested it without any config and it displays buttons. It doesn't even show buttons when I remove the confirmButtonText and declineButtonText.

**Comment by bibizio** [comment]
Hi! As it says in the readme, the _content_ option is used to define the whole content of the dialog, be it a SvelteComponent or a string interpreted as HTML:

>   // sets the content of the dialog,
  // overwriting the default component (that is DialogContent)
  content?: string | htmlString | SvelteComponent;

so it replaces the default component (and the buttons with it).

If you want to use the default component, you may use the _title_ option:

```
dialogs.confirm({
            title: 'Do you want to delete your account?',
            confirmButtonText: 'Delete',
            declineButtonText: 'Abort',
            closeOnBg: true,
            closeOnEsc: true
        })
```

**Comment by ChristianSch** [comment]
Woops, sorry. Thank you, quite a pitfall.
