### ISSUE TITLE
How to change button default color and text 

### ISSUE THREAD

**Issue by ben-ying** [bibizio/svelte-dialogs#6]
<img width="309" alt="image" src="https://user-images.githubusercontent.com/4661175/220878519-6b8fd3ad-30b6-4bc4-ad05-57e176b5517d.png">
How to change the button background color and text when I use dialogs.alert()?

**Comment by tekhedd** [comment]
You can pass the standard options as a parameter to alert(), confirm(), and I assume all of the other entry points. This lets you set the class and styling. So you can do...

```
  dialogs.alert({
    dialogClass: 'my-dialog',
    confirmButtonClass: 'myclass', // or whichever 'buttonclass" it is for alert
    closeOnEsc: true,
  })
  .catch(catchHandler('alert dialog failed'));
```

(or "await" depending on personal style preference etc)

Then you can do  `.my-dialog { background-color: ...` etc.

(TBH What I haven't figure out is how to *remove* the default styling, ie .dialog__button is always applied and the css is inline, but it's a minor inconvenience and not really a 'blocker'...)

Update/tip: I learned that you can 'revert' individual styles at the point they were applied. In this case the padding was clashing with my app style, so I removed it with:

```
.my-dialog .dialog__button {
  padding: revert; /* remove 0.5em padding from svelte-dialogs */
}
```

I was trying to solve this problem and by *answering this question* I solved my own problem. Now that's the power of free software. :)

HTH peace
